server:
  port: ${PORT:8081}

spring:
  application:
    name: java-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/interswitch}

management:
  endpoints:
    web:
      exposure:
        include: health,info
